blog_zhou/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^user/', include('user.urls', namespace='user')),
    re_path(r'^',include('blogs.urls',namespace='blogs')),
    re_path(r'^search',include('haystack.urls')),# 全文检索框架
]

blogs/urls.py
from django.urls import path,re_path
from blogs.views import UserView,Personal_Blogs_list,DetailView,BlogTypeView,ProxyView,StaticIndex

app_name='[blogs]'



urlpatterns = [
    re_path(r'^personal_center$',UserView.as_view(),name='personal_center'),
    re_path(r'^personal_blogs_list/(?P<page>\d+)*$',Personal_Blogs_list.as_view(),name='pblogs'),
    re_path(r'^detail/(?P<blog_id>\d+)$',DetailView.as_view(),name='detail'),
    re_path(r'^blogtype/(?P<page>.*)$',BlogTypeView.as_view(),name='blogtype'),
    re_path(r'^proxy/(?P<page>\d+)*$',ProxyView.as_view(),name='proxy'),
    re_path(r'^$',StaticIndex.as_view(),name='index')

]

user/urls.py
from django.urls import path,re_path
from user.views import IndexView,LoginView,RegisterView,LogoutView,ActiveView

app_name='[user]'
urlpatterns = [
    re_path(r'^index/(?P<page>\d+)*$',IndexView.as_view(),name='index'),
    re_path(r'^login$',LoginView.as_view(),name='login'),
    re_path(r'^register$',RegisterView.as_view(),name='register'),
    re_path(r'^logout$',LogoutView.as_view(),name='logout'),
    re_path(r'active/(?P<token>.*)',ActiveView.as_view(),name='active')
]

templates/blog_sort.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}博客列表{% endblock name %}
{% block swiper %}<div class="swiper-container"></div>{% endblock swiper %}
{% block right %}{% endblock right %}

{% block arclist %}
   {% if blogs_page %}
<div class="arclist">

        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最新文章
            <small>New Article</small>
        </a></h4>
        <!--列表开始-->
        <ul>

            {% for blog in blogs_page %}
            <li id="New" style="!important; height: 300px;overflow: hidden;

text-overflow: ellipsis;">

                <div class="arc-right">
                    <h4 class="blue-text"><a href="{% url 'blogs:detail' blog.id %}" title="{{ blog.title }}">{{ blog.title }}</a></h4>
                    <p >{{ blog.content|safe }}</p>
                    <ul>
                        <li><a title="{{ blog.author }}&ensp;{{ blog.create_time }} 发表 ">
                            <i class="el-time"></i> {{ blog.update_time }}</a></li>
                        <li><a href="#" title="作者： {{ blog.author }}"><i
                                class="el-user"></i>{{ blog.author }}</a></li>
                        <li><a href="#" title="已有 {{ blog.conment_nums }} 条评论"><i
                                class="el-comment"> {{ blog.conment_nums }}</i></a>
                        </li>
                        <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}
                        </a></li>
                        <li><a href="#" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                    </ul>
                </div>
            </li>
            {% endfor %}
        </ul>

            <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ num_pages }} 页</a></li>
                </ul>
            </div>
            <ul>
       {% if blogs_page.has_previous %}
				<a class="active" href="{% url 'blogs:pblogs' blogs_page.previous_page_number %}"><上一页</a>
                {% endif %}
                {% for pindex in blogs_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				        <a class="active" href="{% url 'blogs:blogtype' pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a class="active" href="{% url 'blogs:blogtype' pindex %}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if blogs_page.has_next %}
				<a class="active" href="{% url 'blogs:blogtype' blogs_page.next_page_number %}">下一页></a>
                {% endif %}


            </ul>
        </div>

    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}
{% endblock arclist %}

templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}博客列表{% endblock name %}
{% block css %}
    <link rel="stylesheet" href="/static/css/markdown.css">
    <link rel="stylesheet" href="/static/prism/prism.css">

    <script src="/static/prism/prism.js" charset="utf-8"></script>

    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$', '$']]},
            messageStyle: "none"
        });
    </script>

{% endblock %}
{% block swiper %}{% endblock swiper %}
{#{% block right %}{% endblock right %}#}

{% block arclist %}
<div class="container">
     <article>
         <h3 class="arc-title index-title">{{ blog.title }}</h3>

         <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ blog.author }}发表于{{ blog.create_time }}"><i class="el-time"></i>
                        <time>{{ blog.create_time }}</time>
                    </a></li><!--列表开始-->
                           <li><a title="已有 {{ blog.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ blog.read_nums }}</a></li>
                            <li><a href="#"><i class="el-user"></i>{{ blog.author }}</a></li>
                </ul>
            </div>
            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;">目录[-]</b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ blog.content|safe }}
                </div>
            </div>
                <!--分享-->
            <div class="article-fx"><a class="fx-btn img-circle" href="javascript:;">分享</a>
                <div class="bd-fx arc-bdfx">
                    <i class="el-remove fx-close"></i>
                    <ul class="bdsharebuttonbox">
                        <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                        <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                        <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                        <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
                    </ul>
                    <script>
                        window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "2",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "32"
                        }, "share": {}
                    };
                    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
                    </script>
                </div>
            </div>

 </article>
{#    {% else %}#}
{#    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>#}
{#    {% endif %}#}
    <script>
        function GenerateContentList() {
            $(".post-content").find("h2,h3").each(function (i, item) {
                var tag = $(item).get(0).localName;
                $(item).attr("id", "wow" + i);
                $("#AnchorContent").append('<li><a class="new' + tag + ' anchor-link"  href="#wow' + i + '">' + $(this).text() + '</a></li>');
                $(".newh2").css("margin-left", 0);
                $(".newh3").css("margin-left", 20);
                $(".newh4").css("margin-left", 40);
                $(".newh5").css("margin-left", 60);
                $(".newh6").css("margin-left", 80);
            });
            $("#AnchorContentToggle").click(function () {
                var text = $(this).html();
                if (text == "目录[-]") {
                    $(this).html("目录[+]");
                    $(this).attr({"title": "展开"});
                } else {
                    $(this).html("目录[-]");
                    $(this).attr({"title": "收起"});
                }
                $("#AnchorContent").toggle();
            });
        }
        GenerateContentList();
    </script>
</div>
{% endblock arclist %}

templates/detail00.html
{#{% extends 'base.html' %}#}
{#{% load staticfiles %}#}
{#{% block name %}博客列表{% endblock name %}#}
{#{% block swiper %}{% endblock swiper %}#}
{#{% block right %}{% endblock right %}#}
{##}
{#{% block arclist %}#}
{##}
{#<div class="arclist">#}
{##}
{#        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最新文章#}
{#            <small>New Article</small>#}
{#        </a></h4>#}
{#        <!--列表开始-->#}
{#        <ul>#}
{##}
{#            {% for blog in blogs_page %}#}
{#            <li id="New">#}
{##}
{#                <div class="arc-right">#}
{#                    <h4 class="blue-text"><a href="{% url 'blogs:detail' blog.id %}" title="{{ blog.title }}">{{ blog.title }}</a></h4>#}
{#                    {{ blog.content|safe }}#}
{#                    <ul>#}
{#                        <li><a title="{{ blog.author }}&ensp;{{ blog.create_time }} 发表 ">#}
{#                            <i class="el-time"></i> {{ blog.update_time }}</a></li>#}
{#                        <li><a href="#" title="作者： {{ blog.author }}"><i#}
{#                                class="el-user"></i>{{ blog.author }}</a></li>#}
{#                        <li><a href="#" title="已有 {{ blog.conment_nums }} 条评论"><i#}
{#                                class="el-comment"> {{ blog.conment_nums }}</i></a>#}
{#                        </li>#}
{#                        <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}#}
{#                        </a></li>#}
{#                        <li><a href="#" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{##}
{#    {% else %}#}
{#    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>#}
{#    {% endif %}#}
{#{% endblock arclist %}#}


{#{% extends 'base.html' %}#}
{#{% load staticfiles %}#}
{#{% block name %}博客列表{% endblock name %}#}
{#{% block swiper %}{% endblock swiper %}#}
{#{% block right %}{% endblock right %}#}
{##}
{#{% block arclist %}#}
{##}
{#<div class="arclist">#}
{##}
{#        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最新文章#}
{#            <small>New Article</small>#}
{#        </a></h4>#}
{#        <!--列表开始-->#}
{##}
{##}
{#            {% for blog in blogs_page %}#}
{##}
{##}
{##}
{#                    <h4 class="blue-text"><a href="{% url 'blogs:detail' blog.id %}" title="{{ blog.title }}">{{ blog.title }}</a></h4>#}
{#                    <p>{{ blog.content|safe }}</p>#}
{##}
{##}
{#    {% else %}#}
{#    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>#}
{#    {% endif %}#}
{#{% endblock arclist %}#}

{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}博客列表{% endblock name %}
{#{% block right %}{% endblock right %}#}
{% block arclist %}{% endblock arclist %}
{% block swiper %}
<div class="container">
    <div class="mysection content">
        <article>
            <h3 class="arc-title index-title">{{ blog.title }} </h3>
            <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ blog.author }}发表于{{ blog.edit_time }}"><i class="el-time"></i>
                        <time>{{ blog.edit_time }}</time>
                    </a></li>
                    <li><a href="#"><i class="el-user"></i>{{ blog.author }}</a></li>
                    <li><a href="#Coon" title="转到评论"><i class="el-comment"></i>{{ blog.conment_nums }}条</a></li>
                    <li><a title="已有 {{ blog.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ blog.read_nums }}</a></li>
                </ul>
            </div>

            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;">目录[-]</b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ blog.content|safe }}
                </div>
            </div>
            <!--分享-->
            <div class="article-fx"><a class="fx-btn img-circle" href="javascript:;">分享</a>
                <div class="bd-fx arc-bdfx">
                    <i class="el-remove fx-close"></i>
                    <ul class="bdsharebuttonbox">
                        <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                        <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                        <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                        <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
                    </ul>
                    <script>
                        window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "2",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "32"
                        }, "share": {}
                    };
                    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
                    </script>
                </div>
            </div>
            <!--END 分享-->
{#            <div class="cyReward " style="text-align: center">#}
{#                <div id="cyReward" role="cylabs" data-use="reward" sid="{{ source_id }}"></div>#}
{##}
{#            </div>#}

            <hr>


{#            <!--标签-->#}
{#            <div class="article_tag">#}
{#                <ul>#}
{#                    <li><a href="{% url "blogs:detail" pk=article.category_id %}"#}
{#                           title="归类：{{ article.category.name }}">{{ article.category.name }}</a></li>#}
{#                    {% for tag in article.tag.all %}#}
{#                        <li><a href="{% url "blog:tag" tag.id %}"#}
{#                               title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a>&nbsp;</li>#}
{#                    {% endfor %}#}
{#                </ul>#}
{#            </div>#}
{##}
{#            <div class="cyEmoji" style="text-align: center">#}
{#                <div id="cyEmoji" role="cylabs" data-use="emoji" sid="{{ source_id }}"></div>#}
{#            </div>#}
{##}
{#        </article>#}
{##}
{#        <!--评论表单-->#}
{#        {% include "message.html" %}#}
{##}
{#            <script type="text/javascript" charset="utf-8" src="https://changyan.itc.cn/js/lib/jquery.js"></script>#}
{#        <script type="text/javascript" charset="utf-8"#}
{#                src="https://changyan.sohu.com/js/changyan.labs.https.js?appid=cytzXhLuB"></script>#}
{#    </div>#}







    <script>
        function GenerateContentList() {
            $(".post-content").find("h2,h3").each(function (i, item) {
                var tag = $(item).get(0).localName;
                $(item).attr("id", "wow" + i);
                $("#AnchorContent").append('<li><a class="new' + tag + ' anchor-link"  href="#wow' + i + '">' + $(this).text() + '</a></li>');
                $(".newh2").css("margin-left", 0);
                $(".newh3").css("margin-left", 20);
                $(".newh4").css("margin-left", 40);
                $(".newh5").css("margin-left", 60);
                $(".newh6").css("margin-left", 80);
            });
            $("#AnchorContentToggle").click(function () {
                var text = $(this).html();
                if (text == "目录[-]") {
                    $(this).html("目录[+]");
                    $(this).attr({"title": "展开"});
                } else {
                    $(this).html("目录[-]");
                    $(this).attr({"title": "收起"});
                }
                $("#AnchorContent").toggle();
            });
        }
        GenerateContentList();
    </script>
</div>
{#{% endblock %}#}

{% endblock swiper %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block logo %}{% endblock logo %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock css %}
{% block arclist %}
<div class="arclist"></div>
{% endblock arclist %}
{% block swiper %}
<div class="wrap" id="wrap">
	<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">登录</p>
			</div>
			<!-- 输入框 -->
        <form method="post">
            {% csrf_token %}
			<div class="lgD">

				<input type="text"
					placeholder="输入用户名"  name="username"/>
			</div>
			<div class="lgD">

				<input type="password"
					placeholder="输入用户密码" name="pwd" />
			</div>
			<div class="logC">
                <input type="submit" name="" value="登录 " >
			</div>
            </form>
        <h3>{{ errmsg }}</h3>
        <h3>{{ msg }}</h3>
		</div>
</div>
{% endblock swiper %}

templates/message.html
<h3 class="form-btn blue-text"><a href="javascript:;"><i class="el-edit"></i>我要留言 / 展开表单</a></h3>
<!--高速版-->
<div id="SOHUCS" ></div>
<script charset="utf-8" type="text/javascript" src="http://changyan.sohu.com/upload/changyan.js" ></script>
<script type="text/javascript">
window.changyan.api.config({
appid: 'cytzXhLuB',
conf: '33441587af9325c7608054b22512976d'
});
</script>

templates/personal_blogs_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}博客列表{% endblock name %}
{% block swiper %}{% endblock swiper %}
{% block right %}{% endblock right %}

{% block arclist %}
    {% if blogs_page %}
<div class="arclist">

        <h4 class="index-title homeh4"><a href=""><i class="el-certificate"></i>最新文章
            <small>New Article</small>
        </a></h4>
        <!--列表开始-->
        <ul>

            {% for blog in blogs_page %}
                <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ blog.author }}发表于{{ blog.create_time }}"><i class="el-time"></i>
                        <time>{{ blog.create_time }}</time>
                    </a></li><!--列表开始-->
                           <li><a title="已有 {{ blog.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ blog.read_nums }}</a></li>
                            <li><a href="#"><i class="el-user"></i>{{ blog.author }}</a></li>
                </ul>
            </div>
            <li id="New" style="!important; height: 300px;overflow: hidden;

text-overflow: ellipsis;">

                <div class="arc-right">
                    <h4 class="blue-text"><a href="{% url 'blogs:detail' blog.id %}" title="{{ blog.title }}">{{ blog.title }}</a></h4>
                    <p >{{ blog.content|safe }}</p>
                    <ul>
                        <li><a title="{{ blog.author }}&ensp;{{ blog.create_time }} 发表 ">
                            <i class="el-time"></i> {{ blog.update_time }}</a></li>
                        <li><a href="#" title="作者： {{ blog.author }}"><i
                                class="el-user"></i>{{ blog.author }}</a></li>
                        <li><a href="#" title="已有 {{ blog.conment_nums }} 条评论"><i
                                class="el-comment"> {{ blog.conment_nums }}</i></a>
                        </li>
                        <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}
                        </a></li>
                        <li><a href="#" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                    </ul>
                </div>
            </li>
            {% endfor %}
        </ul>

            <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ num_pages }} 页</a></li>
                </ul>
            </div>
            <ul>
       {% if blogs_page.has_previous %}
				<a class="active" href="{% url 'blogs:pblogs' blogs_page.previous_page_number %}"><上一页</a>
                {% endif %}
                {% for pindex in blogs_page.paginator.page_range %}
                    {% if pindex == blogs_page.number %}
				        <a class="active" href="{% url 'blogs:pblogs' pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a class="active" href="{% url 'blogs:pblogs' pindex %}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if blogs_page.has_next %}
				<a class="active" href="{% url 'blogs:pblogs' blogs_page.next_page_number %}">下一页></a>
                {% endif %}


            </ul>
        </div>

    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}
{% endblock arclist %}

templates/proxy.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}博客列表{% endblock name %}
{% block swiper %}{% endblock swiper %}
{% block right %}{% endblock right %}
{% block arclist %}
<div class="arclist">
        <ul>
            {% for proxy in proxis_page %}
            <li>ip:{{ proxy.ip_address }}---端口:{{ proxy.port }}---地址:{{ proxy.address }}---是否匿名:{{ proxy.anonymous }}---类型:{{ proxy.type }}---存活时间:{{ proxy.alivetiem }}</li>
            {% endfor %}
        </ul>

</div>
            </ul>

            <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ num_pages }} 页</a></li>
                </ul>
            </div>
            <ul>
       {% if proxis_page.has_previous %}
				<a class="active" href="{% url 'blogs:proxy' proxis_page.previous_page_number %}"><上一页</a>
                {% endif %}
                {% for pindex in proxis_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				        <a class="active" href="{% url 'blogs:proxy' pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a class="active" href="{% url 'blogs:proxy' pindex %}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if proxis_page.has_next %}
				<a class="active" href="{% url 'blogs:proxy' proxis_page.next_page_number %}">下一页></a>
                {% endif %}



{% endblock arclist %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block logo %}{% endblock logo %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock css %}
{% block swiper %}

<div class="wrap" id="wrap">
	<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">注册用户</p>
			</div>
			<!-- 输入框 -->
        <form method="post">
            {% csrf_token %}
            <div class="lgD">

				<input type="text"
					placeholder="输入用户名" name="user_name"/>
			</div>
			<div class="lgD">

				<input type="password"
					placeholder="输入用户密码" name="pwd" />
			</div>
			<div class="lgD">

				<input type="password"
					placeholder="确认密码" name="cpwd" />
			</div>
			<div class="lgD">

				<input type="text"
					placeholder="输入邮箱" name="email"/>
			</div>
			<div class="logC">
                <input type="submit" name="" value="注 册  " >
			</div>
		</form>
        <h3>{{ errmsg }}</h3>
    </div>

</div>



{% endblock swiper %}

templates/test.html
{% load staticfiles %}
<html>
<head>
    <title>自定义使用tinymce</title>
    <script type="text/javascript" src='{% static '/js/tiny_mce_src.js' %}'></script>
    <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':800,
            'height':800
        });
    </script>
</head>
<body>
<form method="post" action="#">
    <input type="text" name="title">
    <textarea name='gcontent'>哈哈，这是啥呀</textarea>
</form>
</body>
</html>

templates/user_center.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block name %}个人中心发布博客{% endblock name %}
{% block js %}
    <script type="text/javascript" src='{% static '/js/tiny_mce_src.js' %}'></script>
     <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':670,
            'height':800
        });
    </script>
{% endblock js %}

<!--主题框架开始-->

    <!--左侧开始-->
    
    
    {% block swiper %}
{{ errmsg }}

<div class="container">
{#            <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section><br>#}
        <form action="" method="post">
            {% csrf_token %}
            <div class="search-index">
                {%autoescape off%}
                <input name="title" type="text" placeholder="请输入标题" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入标题'"/>
                {%endautoescape%}

{#                <i class="el-search"><input value=" " type="submit"/></i>#}
            </div>
            {%autoescape off%}
                <textarea name='gcontent'>这里开始写你的博客吧</textarea><br>
             {%endautoescape%}
            {% for category in categorys %}
            <lable>{{ category.name }}</lable><input value="{{ category.name }}" type="radio" name="category">
            {% endfor %}
             <div class="search-index">

            <input value="点击发表博客" type="submit" >
            </div>

</div>
    </section>
        </form> 
    {% endblock swiper %}
{% block right %}{% endblock right %}